### 1.加载数据

In [1]:
import numpy as np
import pandas as pd

job = pd.read_csv('./job.csv')

display(job.shape,job.head())

(3683, 12)

,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail
0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,25k-35k,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...
1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,25k-45k,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...
2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...
3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...
4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,15k-30k,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...

### 2 删除重复数据

In [5]:
d = job.duplicated()
d.sum() #False=0,True=1

np.int64(176)

In [17]:
job.drop_duplicates(inplace = True)

In [18]:
job.duplicated().sum()

np.int64(0)

### 3 数据清洗

In [19]:
job.head()

,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail
0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,25k-35k,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...
1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,25k-45k,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...
2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...
3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...
4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,15k-30k,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...

#### 3.1 过滤非数据分析的岗位

In [20]:
s2 = job['positionName'].str #筛选职位名这一列的所有字符串
s2

In [21]:
cond = s2.contains('数据分析')

In [22]:
job[cond]

,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail
0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,25k-35k,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...
1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,25k-45k,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...
2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...
3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...
4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,15k-30k,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...
...,...,...,...,...,...,...,...,...,...,...,...,...
3352,数据分析师,华泛信息,苏州,2000人以上,大专,不需要融资,"移动互联网,其他",10k-15k,1-3年,NaN,"[""技能培训"",""节日礼物"",""带薪年假"",""绩效奖金""]","\n岗位职责：\n深入了解项目组的业务需求,在此基础上进行数据收集、数据分析、商业报告的撰写..."
3353,大数据分析师,德融嘉信,苏州,50-150人,本科,不需要融资,移动互联网,6k-12k,1-3年,NaN,[],\n岗位职责：\n1. 开展业务专题分析，使用数据挖掘各类算法构建相关的业务模型，完成业务分...
3580,ETL/大数据/数据分析/实施,格蒂电力,天津,500-2000人,大专,未融资,企业服务,6k-12k,3-5年,NaN,"[""技能培训"",""带薪年假"",""绩效奖金"",""岗位晋升""]",\n工作职责\n1. 负责数据接入、数据整合中的链路配置与调度配置工作。\n职位要求\n...
3581,数据分析师,吉城美家,天津,2000人以上,本科,未融资,移动互联网,7k-14k,1-3年,NaN,"[""五险一金"",""岗位晋升""]",\n负责站点日常数据分析、提前通过数据分析对业务有预测性、通过数据说话、解决站点管理问题、\n
3582,数据分析支持,云链供应链,天津,15-50人,本科,未融资,"金融,企业服务",4k-6k,1-3年,NaN,[],\n 岗位职责：\n1、负责部门日常数据报表的制定、维护、优化；\n2、支持运...

In [23]:
job = job[cond]

In [24]:
job.reset_index(inplace = True)

In [25]:
job

,index,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail
0,0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,25k-35k,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...
1,1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,25k-45k,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...
2,2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...
3,3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,15k-25k,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...
4,4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,15k-30k,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,3352,数据分析师,华泛信息,苏州,2000人以上,大专,不需要融资,"移动互联网,其他",10k-15k,1-3年,NaN,"[""技能培训"",""节日礼物"",""带薪年假"",""绩效奖金""]","\n岗位职责：\n深入了解项目组的业务需求,在此基础上进行数据收集、数据分析、商业报告的撰写..."
1648,3353,大数据分析师,德融嘉信,苏州,50-150人,本科,不需要融资,移动互联网,6k-12k,1-3年,NaN,[],\n岗位职责：\n1. 开展业务专题分析，使用数据挖掘各类算法构建相关的业务模型，完成业务分...
1649,3580,ETL/大数据/数据分析/实施,格蒂电力,天津,500-2000人,大专,未融资,企业服务,6k-12k,3-5年,NaN,"[""技能培训"",""带薪年假"",""绩效奖金"",""岗位晋升""]",\n工作职责\n1. 负责数据接入、数据整合中的链路配置与调度配置工作。\n职位要求\n...
1650,3581,数据分析师,吉城美家,天津,2000人以上,本科,未融资,移动互联网,7k-14k,1-3年,NaN,"[""五险一金"",""岗位晋升""]",\n负责站点日常数据分析、提前通过数据分析对业务有预测性、通过数据说话、解决站点管理问题、\n
1651,3582,数据分析支持,云链供应链,天津,15-50人,本科,未融资,"金融,企业服务",4k-6k,1-3年,NaN,[],\n 岗位职责：\n1、负责部门日常数据报表的制定、维护、优化；\n2、支持运...

#### 3.2 薪水处理【字符串--->数值】

In [28]:
job['salary'].str.contains('K').sum()

np.int64(1)

In [31]:
#大写转小写
s = job['salary'].str
s.lower()

0       25k-35k
1       25k-45k
2       15k-25k
3       15k-25k
4       15k-30k
         ...
1647    10k-15k
1648     6k-12k
1649     6k-12k
1650     7k-14k
1651      4k-6k
Name: salary, Length: 1652, dtype: str

In [32]:
#正则表达式的应用
import re
s = '20k-25k'
re.findall(r'(\d+)k-(\d+)k',s)

[('20', '25')]

In [33]:
salary = job['salary'].str.lower()
salary_str = salary.str
salary_str.findall(r'(\d+)k-(\d+)k')

0       [(25, 35)]
1       [(25, 45)]
2       [(15, 25)]
3       [(15, 25)]
4       [(15, 30)]
           ...
1647    [(10, 15)]
1648     [(6, 12)]
1649     [(6, 12)]
1650     [(7, 14)]
1651      [(4, 6)]
Name: salary, Length: 1652, dtype: object

In [35]:
salary_str.extract(r'(\d+)k-(\d+)k') #数据输出为DataFrame

       0   1
0     25  35
1     25  45
2     15  25
3     15  25
4     15  30
...   ..  ..
1647  10  15
1648   6  12
1649   6  12
1650   7  14
1651   4   6

[1652 rows x 2 columns]

In [40]:
salary_str.extract(r'(\d+)k-(\d+)k').astype(np.int16).mean(axis = 1)

0       30.0
1       35.0
2       20.0
3       20.0
4       22.5
        ...
1647    12.5
1648     9.0
1649     9.0
1650    10.5
1651     5.0
Length: 1652, dtype: float64

In [41]:
job['salary'] = job['salary'].str.lower().str.extract(r'(\d+)k-(\d+)k').astype(np.int16).mean(axis = 1)

In [43]:
job.head()

,index,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail
0,0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,30.0,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...
1,1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,35.0,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...
2,2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,20.0,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...
3,3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,20.0,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...
4,4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,22.5,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...

#### 3.3 job_detail中提取技能

In [44]:
s = job['job_detail'].str.lower()
s.isna().sum()

np.int64(0)

In [45]:
job['job_detail'] = job['job_detail'].str.lower()
job['Python'] = job['job_detail'].map(lambda x : 1 if ('python' in x) else 0)
job['SQL'] = job['job_detail'].map(lambda x : 1 if ('sql' in x) or ('hive' in x) else 0)
job['Tableau'] = job['job_detail'].map(lambda x : 1 if ('tableau' in x) else 0)
job['Excel'] = job['job_detail'].map(lambda x : 1 if ('excel' in x) else 0)
job['SPSS/SAS'] = job['job_detail'].map(lambda x : 1 if ('spss' in x) or ('sas' in x) else 0)
job.head()

,index,positionName,companyShortName,city,companySize,education,financeStage,industryField,salary,workYear,hitags,companyLabelList,job_detail,Python,SQL,Tableau,Excel,SPSS/SAS
0,0,高级数据分析师,拉勾网,北京,500-2000人,本科,D轮及以上,企业服务,30.0,5-10年,"[""免费下午茶"",""ipo倒计时"",""bat背景"",""地铁周边"",""每天管两餐"",""定期团建...","[""五险一金"",""弹性工作"",""带薪年假"",""免费两餐""]",\n1.搭建数据指标框架，完整并准确反映业务趋势和变化，及时发现和定位问题\n2.独立完成数...,1,1,0,0,0
1,1,数据分析师,OK Group,北京,500-2000人,大专,B轮,金融,35.0,5-10年,NaN,"[""节日礼物"",""年度旅游"",""扁平管理"",""领导好""]",\n工作职责：\n1. 负责建立交易平台日常分析体系，包括核心指标体系、报表体系，专题活动分...,0,1,0,0,0
2,2,高级数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,20.0,3-5年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n职位描述：1.对亿计的办公用户数据进行深度挖掘，引导产品、运营，并能实际应用到业务中带来...,1,1,0,0,0
3,3,数据分析师,金山办公软件,北京,2000人以上,本科,上市公司,移动互联网,20.0,1-3年,NaN,"[""年底双薪"",""节日礼物"",""技能培训"",""绩效奖金""]",\n工作职责：-负责日常运营、业务数据等分析-针对产品需求做深入的数据分析报告，分析用户行为...,0,1,0,0,1
4,4,数据分析师,京东集团,北京,2000人以上,本科,上市公司,电商,22.5,3-5年,"[""免费班车"",""免费体检"",""地铁周边""]","[""五险一金"",""带薪年假"",""免费班车"",""定期体检""]",\n【数据分析师岗】\n岗位要求：\n1、构建及维护客户体验相关数据报表平台；\n2、与大数...,0,1,1,1,1

#### 3.4 处理行业信息

In [56]:
def convert(item):
    items = item.split(',')
    if items[0] == '移动互联网' and len(items) > 1:
        return items[1]
    else:
        return items[0]

In [58]:
industry = job['industryField'].map(convert)

In [59]:
industry.value_counts()

industryField
电商            237
金融            223
数据服务          205
文娱丨内容         120
企业服务          119
移动互联网         117
消费生活           90
社交             89
游戏             84
教育             80
硬件             45
其他             41
汽车丨出行          30
医疗丨健康          27
信息安全           24
广告营销           24
人工智能           19
房产家居           14
物流丨运输           9
工具              7
旅游              7
软件开发            7
通讯电子            6
物联网             5
医疗健康            3
电子商务            3
数据服务、教育         3
区块链             2
金融 广告营销         2
电子商务 移动互联网      2
数据服务、企业服务       1
企业服务 数据服务       1
文化娱乐 广告营销       1
移动互联网 数据服务      1
人工智能、数据服务       1
信息安全、数据服务       1
金融、电商           1
数据服务、人工智能       1
Name: count, dtype: int64