### 1 pandas数据结构

#### 1.1 Series[一维]

In [1]:
import numpy as np
import pandas as pd

In [10]:
s = pd.Series(data = np.random.randint(0,150,size = 10),
          index = list('ABCDEFHIJK'),
          name = 'Python')
s

A    100
B    131
C     94
D     65
E    128
F     78
H     91
I     48
J      6
K    132
Name: Python, dtype: int32

In [12]:
s.values #获取的数据，就是Numpy数组

array([100, 131,  94,  65, 128,  78,  91,  48,   6, 132], dtype=int32)

#### 1.2 DataFrame[二维】

In [14]:
df = pd.DataFrame({'Python':[30,80,100],'Math':[100,20,149]})
df

   Python  Math
0      30   100
1      80    20
2     100   149

In [16]:
df2 = pd.DataFrame(data = np.random.randint(0,150,size = (10,3)),
                   index = list('ABCDEFHIJK'), #行索引
                   columns = ['Python','Math','En'])
df2

   Python  Math   En
A      73   135   91
B      36   148   23
C      56    83   52
D      25   131   78
E      47   121  112
F      89    31  109
H      59     5  103
I      21   132   33
J      53    79  102
K      73    36  149

In [17]:
df3 = pd.DataFrame(data = np.random.randint(0,150,size = (1000,3)),
                   columns = ['Python','Math','En'])
df3

     Python  Math   En
0        56   112  140
1        89    58   80
2       140    43  104
3        63    82  129
4        78     3  111
..      ...   ...  ...
995      73    81   40
996     122    40   44
997      94    27   38
998     112    81  110
999      33   149    8

[1000 rows x 3 columns]

In [18]:
df3['Python'] #取出的一列，是Series
#DataFrame是由多个Series组成的

0       56
1       89
2      140
3       63
4       78
      ...
995     73
996    122
997     94
998    112
999     33
Name: Python, Length: 1000, dtype: int32

In [20]:
df3.values #Numpy数组，就是二维数组

array([[ 56, 112, 140],
       [ 89,  58,  80],
       [140,  43, 104],
       ...,
       [ 94,  27,  38],
       [112,  81, 110],
       [ 33, 149,   8]], shape=(1000, 3), dtype=int32)