### 1 数据选择

#### 1.1 位置选择

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame(np.random.randint(0,150,size = (10,3)),
                  index = list('ABCDEFHIJK'),
                  columns = ('Python','Math','En'))
df

   Python  Math   En
A      10    50  105
B      90    23   45
C      27    33   20
D      82    18    3
E      29   101   46
F      90    16   48
H     140    32   77
I      55   122   54
J      62    50   83
K     138    85   92

In [5]:
df.loc['A']

Python     10
Math       50
En        105
Name: A, dtype: int32

In [6]:
df.iloc[0]

Python     10
Math       50
En        105
Name: A, dtype: int32

In [7]:
df.iloc[[0,2,4,6]]

   Python  Math   En
A      10    50  105
C      27    33   20
E      29   101   46
H     140    32   77

In [8]:
df.iloc[2:8]

   Python  Math  En
C      27    33  20
D      82    18   3
E      29   101  46
F      90    16  48
H     140    32  77
I      55   122  54

In [9]:
df.iloc[2:8,::2]

   Python  En
C      27  20
D      82   3
E      29  46
F      90  48
H     140  77
I      55  54

In [10]:
df.loc['E','Math']

np.int32(101)

In [11]:
print(df.iloc[4,1])

101

#### 1.2 boolean索引

In [12]:
df

   Python  Math   En
A      10    50  105
B      90    23   45
C      27    33   20
D      82    18    3
E      29   101   46
F      90    16   48
H     140    32   77
I      55   122   54
J      62    50   83
K     138    85   92

In [13]:
cond = df['Python'] >100
cond

A    False
B    False
C    False
D    False
E    False
F    False
H     True
I    False
J    False
K     True
Name: Python, dtype: bool

In [14]:
df[cond]

   Python  Math  En
H     140    32  77
K     138    85  92

In [15]:
cond2 = df['Math'] > 100
cond3 = cond|cond2
df[cond3]

   Python  Math  En
E      29   101  46
H     140    32  77
I      55   122  54
K     138    85  92

In [16]:
cond4 = pd.DataFrame(cond3)
display(cond3,cond4)
df[cond4] #获取数据时，只能是Series

A    False
B    False
C    False
D    False
E     True
F    False
H     True
I     True
J    False
K     True
dtype: bool

       0
A  False
B  False
C  False
D  False
E   True
F  False
H   True
I   True
J  False
K   True

   Python  Math  En
A     NaN   NaN NaN
B     NaN   NaN NaN
C     NaN   NaN NaN
D     NaN   NaN NaN
E     NaN   NaN NaN
F     NaN   NaN NaN
H     NaN   NaN NaN
I     NaN   NaN NaN
J     NaN   NaN NaN
K     NaN   NaN NaN

In [17]:
#条件判断，问问行索引是否在列表中
nd = df.index.isin(['A','F','J'])
df[nd]

   Python  Math   En
A      10    50  105
F      90    16   48
J      62    50   83

#### 1.3 赋值操作

In [18]:
df.loc['C','En'] *= 10
df

   Python  Math   En
A      10    50  105
B      90    23   45
C      27    33  200
D      82    18    3
E      29   101   46
F      90    16   48
H     140    32   77
I      55   122   54
J      62    50   83
K     138    85   92

In [19]:
cond = df.Python <= 60
#df[cond,'Python']会报错，因为cond不是字段
df.loc[cond,'Python'] = 60
df

   Python  Math   En
A      60    50  105
B      90    23   45
C      60    33  200
D      82    18    3
E      60   101   46
F      90    16   48
H     140    32   77
I      60   122   54
J      62    50   83
K     138    85   92

### 2 数据转换

#### 2.1 轴和元素的替换

In [20]:
#重命名索引
df2 = df.rename(index = {'A':'AA','B':'BB'},columns = {'Python':'人工智能'})
df2

    人工智能  Math   En
AA    60    50  105
BB    90    23   45
C     60    33  200
D     82    18    3
E     60   101   46
F     90    16   48
H    140    32   77
I     60   122   54
J     62    50   83
K    138    85   92

In [21]:
#值替换
df.replace(60,66)

   Python  Math   En
A      66    50  105
B      90    23   45
C      66    33  200
D      82    18    3
E      66   101   46
F      90    16   48
H     140    32   77
I      66   122   54
J      62    50   83
K     138    85   92

In [22]:
df

   Python  Math   En
A      60    50  105
B      90    23   45
C      60    33  200
D      82    18    3
E      60   101   46
F      90    16   48
H     140    32   77
I      60   122   54
J      62    50   83
K     138    85   92

In [23]:
#值替换
#操作之后，可以赋值给任何变量，没有接收
df.replace(60,66) #不是原数据的基础上进行的修改

   Python  Math   En
A      66    50  105
B      90    23   45
C      66    33  200
D      82    18    3
E      66   101   46
F      90    16   48
H     140    32   77
I      66   122   54
J      62    50   83
K     138    85   92

In [24]:
df.replace(60,66,inplace = True) #inplace这个参数，会使原数据发生变化

   Python  Math   En
A      66    50  105
B      90    23   45
C      66    33  200
D      82    18    3
E      66   101   46
F      90    16   48
H     140    32   77
I      66   122   54
J      62    50   83
K     138    85   92

In [25]:
df.replace([66,50],1024,inplace = True) #一次替换多个

   Python  Math   En
A    1024  1024  105
B      90    23   45
C    1024    33  200
D      82    18    3
E    1024   101   46
F      90    16   48
H     140    32   77
I    1024   122   54
J      62  1024   83
K     138    85   92

In [26]:
df.replace({1024:150,111:80},inplace = True) #给一个字典，个性化修改

   Python  Math   En
A     150   150  105
B      90    23   45
C     150    33  200
D      82    18    3
E     150   101   46
F      90    16   48
H     140    32   77
I     150   122   54
J      62   150   83
K     138    85   92

In [27]:
df.replace({'Math':54},120)

   Python  Math   En
A     150   150  105
B      90    23   45
C     150    33  200
D      82    18    3
E     150   101   46
F      90    16   48
H     140    32   77
I     150   122   54
J      62   150   83
K     138    85   92

#### 2.2 map映射

In [28]:
import numpy as np
import pandas as pd

In [29]:
df

   Python  Math   En
A     150   150  105
B      90    23   45
C     150    33  200
D      82    18    3
E     150   101   46
F      90    16   48
H     140    32   77
I     150   122   54
J      62   150   83
K     138    85   92

In [30]:
#df['Math']取出了一列，这一列是Series，所以map函数是Series函数
df['Math'].map({150:90,101:120}) #没有特定位置的数会变为NAN

A     90.0
B      NaN
C      NaN
D      NaN
E    120.0
F      NaN
H      NaN
I      NaN
J     90.0
K      NaN
Name: Math, dtype: float64

In [35]:
# 函数名任意，功能自定义
def convert(x): #x代表Math这一列的每一个元素的数值
    if x ==150:
        return 90
    elif x == 101:
        return 120
    else:
        return x
df['Math'].map(convert)

A     90
B     23
C     33
D     18
E    120
F     16
H     32
I    122
J     90
K     85
Name: Math, dtype: int64

In [36]:
df['Math'] = df['Math'].map(convert)

In [37]:
df

   Python  Math   En
A     150    90  105
B      90    23   45
C     150    33  200
D      82    18    3
E     150   120   46
F      90    16   48
H     140    32   77
I     150   122   54
J      62    90   83
K     138    85   92

In [38]:
df['Python'].map(lambda x : 88 if x == 150 else 149)

A     88
B    149
C     88
D    149
E     88
F    149
H    149
I     88
J    149
K    149
Name: Python, dtype: int64

#### 2.3 apply元素改变

In [41]:
#apply的对象是df中的一列Series
df['En'].apply(lambda x : 100 if x < 100 else x)

A    105
B    100
C    200
D    100
E    100
F    100
H    100
I    100
J    100
K    100
Name: En, dtype: int64

In [42]:
df.apply(lambda x : x.median()) #apply的对象是df中的每一列（即其本身）

Python    139.0
Math       59.0
En         65.5
dtype: float64

In [43]:
def convert(x):
    return(x.mean(),x.median(),x.count())
df.apply(convert,axis = 0) #axis为0计算列的结果，为1计算行的结果

   Python  Math    En
0   120.2  62.9  75.3
1   139.0  59.0  65.5
2    10.0  10.0  10.0

In [45]:
df.apply(lambda x: x+100)

   Python  Math   En
A     250   190  205
B     190   123  145
C     250   133  300
D     182   118  103
E     250   220  146
F     190   116  148
H     240   132  177
I     250   222  154
J     162   190  183
K     238   185  192

#### 2.4 transform数据改变

In [54]:
#1.一列执行多项计算
df['Python'].transform([np.sqrt,np.exp]) #Series处理

        sqrt           exp
A  12.247449  1.393710e+65
B   9.486833  1.220403e+39
C  12.247449  1.393710e+65
D   9.055385  4.093997e+35
E  12.247449  1.393710e+65
F   9.486833  1.220403e+39
H  11.832160  6.327432e+60
I  12.247449  1.393710e+65
J   7.874008  8.438357e+26
K  11.747340  8.563248e+59

In [55]:
def convert(x):
    if x.mean() > 5:
        x *= 10
    else:
        x *= -10
    return x

In [59]:
#2.多项执行不同计算
df.transform({'Python':convert,'Math':np.sqrt,'En':np.sin}) #DataFrame处理

   Python       Math        En
A    1500   9.486833 -0.970535
B     900   4.795832  0.850904
C    1500   5.744563 -0.873297
D     820   4.242641  0.141120
E    1500  10.954451  0.901788
F     900   4.000000 -0.768255
H    1400   5.656854  0.999520
I    1500  11.045361 -0.558789
J     620   9.486833  0.968364
K    1380   9.219544 -0.779466

#### 2.5 抽样和独热编码

In [ ]:
df = pd.DataFrame(data = np.random.randint(0,10,size = (10,3)),
                  index = list('ABCDEFHIJK'),
                  columns = ['Python','Tensorflow','Keras'])

In [60]:
index = np.random.permutation(10) #随机重排0~9数字
print(index)
df.take(index) #重排DataFrame

[7 0 1 8 5 4 3 9 6 2]

   Python  Math   En
I     150   122   54
A     150    90  105
B      90    23   45
J      62    90   83
F      90    16   48
E     150   120   46
D      82    18    3
K     138    85   92
H     140    32   77
C     150    33  200

In [61]:
df.take(np.random.randint(0,10,size = 15)) #随机抽样

   Python  Math  En
E     150   120  46
I     150   122  54
D      82    18   3
K     138    85  92
K     138    85  92
E     150   120  46
H     140    32  77
K     138    85  92
J      62    90  83
E     150   120  46
I     150   122  54
K     138    85  92
I     150   122  54
J      62    90  83
D      82    18   3

In [62]:
#哑变量，独热变量，1表示有，0表示没有
df = pd.DataFrame({'key':['b','b','a','c','a','b']})
pd.get_dummies(df,prefix = '',prefix_sep = '')

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

### 3 分箱操作

In [65]:
df = pd.DataFrame(data = np.random.randint(0,150,size = (100,3)),
                  columns = ['Python','Tensorflow','Keras'])
df

    Python  Tensorflow  Keras
0      120          26     31
1       79          90    100
2       58          34     11
3      111          54    144
4       52          63     69
..     ...         ...    ...
95      89          58    139
96      78          36     77
97       1         136    118
98      55          90     96
99     145          88    101

[100 rows x 3 columns]

In [66]:
#1.等距分箱
pd.cut(df.Python,bins = 3)

0      (99.667, 149.0]
1     (50.333, 99.667]
2     (50.333, 99.667]
3      (99.667, 149.0]
4     (50.333, 99.667]
            ...
95    (50.333, 99.667]
96    (50.333, 99.667]
97     (0.852, 50.333]
98    (50.333, 99.667]
99     (99.667, 149.0]
Name: Python, Length: 100, dtype: category
Categories (3, interval[float64, right]): [(0.852, 50.333] < (50.333, 99.667] < (99.667, 149.0]]

In [67]:
#指定距离分箱
pd.cut(df.Keras, #分箱操作
       bins = [0,60,90,120,150], #分箱短点
       right = False, #左闭右开
       labels = ['不及格','中等','良好','优秀']) #分箱后分类

0     不及格
1      良好
2     不及格
3      优秀
4      中等
     ...
95     优秀
96     中等
97     良好
98     良好
99     良好
Name: Keras, Length: 100, dtype: category
Categories (4, str): ['不及格' < '中等' < '良好' < '优秀']

In [68]:
#2.等频分箱
pd.qcut(df.Python,q = 4, #四等分
        labels = ['差','中','良','优']) #分箱后分类

0     优
1     中
2     中
3     良
4     中
     ..
95    良
96    中
97    差
98    中
99    优
Name: Python, Length: 100, dtype: category
Categories (4, str): ['差' < '中' < '良' < '优']